
# We will define all the artifacts(output) of each stages/components(data ingestion, data validations, model_training, model_evaluation, model_deployment)
class DatalIngestionArtifact:...
class DataValidationArtifact:...
class DataTransformationArtifact:...
class ModelTrainerArtifact:...
class ModelEvaluationArtifact:...
class ModelPusherArtifact:...
